### ISSUE TITLE
C-0048 - not working with deployments without volumes key

### ISSUE THREAD

**Issue by betorvs** [kubescape/cel-admission-library#58]
# description

I have been testing and when I run [C-0048](https://github.com/kubescape/cel-admission-library/blob/main/controls/C-0048/policy.yaml) against a deployment that does not have a volume key defined, it fails to evaluate. 

Tested in Kind and here : [playcel.undistro.io validating admission policy](https://playcel.undistro.io/?content=H4sIAAAAAAAAA8VWbW%2FbNhD%2BK4yAwQlg2Wm7DYWAfQicvg1dZjhJ96HuB0q8SGwonkZSTry2%2F31HSpQVd3OBYsgCGOG98p574elTsuFNkiW8ke%2FAWIk6Y1zU0vqjgVJaZ7ij8%2Bz2uZ1JnG%2BerPWt1CJj77iSgmS6PIsGS1Sy2K51DY6TiGdrzZjmNWRsndy2OdiCN5AW6enpj89TAXqb3qG5VciFTe%2Bkq9IKrWs4HWpstbPrxHtQPAdlgzPGCtTOoHojvM9F8NRpca3RhVj3VK%2BN8rqVc43N5vOqzWfc1Gih8IAEFnZeDH5sA0Uwv%2BFStQY6SBl7SaRn19wV1YLuoLxIirC%2FyoDF1hSwahVEXsooq68MtnQtke%2FJffKhEzG2SzgJSUR53QmxAdMjCXaL1YuzqxfrZEowrpfn4Twox6vjJQ0KO4i%2FjoE3jX2UOAQ0Crc1hDJO14khWhbcQk8LDjV5jqSl2sFNqzrGv4af%2B%2Fw%2FSvwfMe8iKwzqjgi6m77vd32WMrhvyLwbn3WC%2BUco3MyPCTv6hU2WKCbs82fW832LzTao2hrsjCt1TOcpOzquuPXHmZ%2BBJc3AyclJ19n%2Bj3QtL8MgXVVggHH6oaafYTXSOVqxbnKY1MxVwOjuI3ZsATot7ti352C4dh%2FY%2B8n5UNTJdLLqKnoJnjgP5ezOl30tO%2BpXzCcfAlCfkSnbS4%2F%2Ff7KfHgd1o8jJ4ybrj%2F4x%2Bu8ytt8KC%2Boln499vNRfVw8g%2Fz8J6MP7HvzJNPFP%2Fu8B1P5GoTdntDl2TbS3Kh489GSUMb80jAYHNs0RXcHrZrdTDghtwwvSEHDDW%2BVGz3pjsPT1OQculNRwCbQlBM38z6enXh5fqYw968iN9Bhe0yJEs30ra%2Bky9iSoWlAEFU0fb9gMb8cIDmMImxXKbdwgqCie8rqhbMDgoOb3l63xlXz60w8j5rXmG9pIPFdjkds2RK7Gnrwg9lIMdJzysCcNhPfsSlLiHIWXMd0qFcXqIabDqAhXTHVcwbQnqREGVspkHXqzLIxvoxKxVJBackC7c%2F4PfjPfOvHyYLyk8OJmfnNzgW5JNQ39FNUOdshXD%2F6nLzu2A1NLHRLyWzdGflAyNhewmY%2BEqcLyoFX8cpAKop7QNrIXqrVk9FIaO4RtfPqNiypn6o5vbRTaogJBnxfmIkDrWzsd2IMeFK2RbksfKQ7u3RjcKMhXhgZkCUaiGEbgGbV1HGMlhknuWRdxrHasFfzZUsg7xlnrKjTyLzAdr0bh1f035pe%2FAbsaMUVrCgAA)

Error found:
```
unexpected error evaluating expression ['Deployment','ReplicaSet','DaemonSet','StatefulSet','Job'].all(kind, object.kind != kind) || object.spec.template.spec.volumes.all(vol, !(has(vol.hostPath))): no such key: volumes
```

Deployment used:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubernetes-bootcamp
  name: kubernetes-bootcamp
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubernetes-bootcamp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubernetes-bootcamp
    spec:
      containers:
      - image: gcr.io/google-samples/kubernetes-bootcamp:v1
        imagePullPolicy: IfNotPresent
        name: kubernetes-bootcamp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

```

Any suggestions?
