### ISSUE TITLE
C-0044 - fails with more than one port in containers.ports

### ISSUE THREAD

**Issue by betorvs** [kubescape/cel-admission-library#59]
# description

I have been testing and when I run [C-0044](https://github.com/kubescape/cel-admission-library/blob/main/controls/C-0044/policy.yaml) against a deployment that does has more than one port configured and it passes. 

Tested it in kind and in [playcel.undistro.io](https://playcel.undistro.io/?content=H4sIAAAAAAAAA9VW3W%2FbNhD%2FVxgBgxPAst20GwoBfQicfg1tajhJ91D3gZYuEhuKp5GUG6%2Ft%2F74jJUqK2roPw4rNLybvi3c%2F%2FY7HT9GOV1ES8Uq8BW0EqoTxrBTGLTXkwljNLa1nt4%2FNTOB892CjboXKEvaWS5GRTuVnwWGFUqT7jSrBclLxZKMYU7yEhG2i23oLJuUVxGm8WDx6FGeg9rEGg7VOwcQfhS3iAo2NK9R2EzlfybcgjQ%2FDWIrKapQvMxdt6WM0VlwptD7Lkem1ls62sLYyyXxe1NsZ1yUaSF0pGaZmnnZxTAWpd7%2FhQtYammIS9oy2TlxymxZLOoMQEcqGo0IB61pCkMWM8HyusaZjafuOwkfvGxVjPdSkJBUh2iuxAt1W4v2W66dnV0830ZTKuF6d%2B3Vn3GHXHlJhZjr11znwqjI%2FJY8MKon7Eggk8thEmvYi5QbafcahpMhha%2BjbwU0tG8F30986%2FH9K%2Fh9w22SWalTNxtvuWsb3PIsZ3FXk3jTOJsLtB0jtzDUIO3rCJivMJuzzZ9bKHcVmjptEIEp9xqU87rZTdnRccNMLZq4PzMmJC3A0Fntft5oy5%2BRWM9c8K1qc0K%2FpDPcrKT2e%2BxZ8o4ChZiVqYH0aTChmC2CUrIvFXoQePGLHBqAx55b9uI26U8e4vJucd5yYTCfrhhCX4Dbnng3N%2BrKlQrP7HbeT975QB%2BiUjdB1%2FydjdC2UlaQg%2F3Gs%2F0B9K5H%2Fa4CPibgkJjs4x3ARu6%2FuIfY%2Fwa%2Bt55%2FDF00jN6neeEzGg5AuzMHA6yk8mnD3phQ5JczNOq3A0ljbItqUl1U%2FCg8oTcVTssjghtfSDmZSpTF3n%2FcceCYJiUsgTDK6sH5bLJw%2BXLEJe9hsd8LV8ILmN%2Br9K1EKm7AH3tSApFJRt%2Fn6sfZqWMHhGvyDAPJ9GH8oKZ%2F8uiI0oAtQ8rvLWrsPefrrLwPhteI7Gqd8K4cqu69oux5GcopAxZDoEHI%2F5DX4y%2FhKEHCW0kuYqqUManm%2FpsNVUV0B6vB%2BaAjXiWImSk%2FNPNWORjliLiE2FIAG%2F%2FwbcRNHnXC4d15ReuFZ8fLmAu2KvqnnUzDz%2FTLIOe5Tcd2SsMeLobIhlCN6L2Vjl9PToTI03lhODLOYIj2YrparXnGQsl%2BNz09ferEFXQrlv9Drpq1X3BYJm2ewmw%2BUscT8oFd4hwkJwS5TJoiXsjbk9Exo0%2BGoHR%2B0DSZn8iPfm6A0aQEZPdb0hS%2Bt7bW4E3d2kNZa2D09%2BSzc2WFxgySfa%2BrYFWiBWdeTD%2BkbhXtFZt3V0oouQp%2F3ojX8WVPKveCstgVq8RfoRlZi5szdW%2F3L38L8fZ6zCwAA)

Deployment used:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubernetes-bootcamp
  name: kubernetes-bootcamp
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubernetes-bootcamp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubernetes-bootcamp
    spec:
      containers:
      - image: gcr.io/google-samples/kubernetes-bootcamp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - name: http
          containerPort: 22
          hostPort: 22
          protocol: TCP
        name: kubernetes-bootcamp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

Any suggestions?
